version: '3.9'
services:
  traefik:
    build: 
      context: ./traefik/
      dockerfile: Dockerfile
    networks:
      - frontend
    depends_on:
      - cloudflare-tunnel
    restart: always
    ports:
      - 80:80
      - 443:443
    command:
      - "--providers.docker=true"
      - "--providers.docker.expsodedBydefault=false"  
      - "--providers.docker.network=proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.vanvaerenbergh.online`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:2023.8.2
    networks:
      - frontend
    restart: unless-stopped
    environment:
     - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
networks:
  frontend:
    external: true
  proxy:
    external: true