#Traefik.yml V2
# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    exposedByDefault: false
## Static configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
# API and dashboard configuration
api:
  dashboard: true
  