#Traefik.yml V2
## Static configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
# API and dashboard configuration
api:
  dashboard: true
  